// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DiamondShopSystem.Data.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public int? CustomerId { get; set; }

    public DateTime? OrderDay { get; set; }

    public string OrderStatus { get; set; }

    public string PaymentMethod { get; set; }

    public string PaymentStatus { get; set; }

    public string ShippingAddress { get; set; }

    public string Discount { get; set; }

    public double? TotalPrice { get; set; }

    public string Note { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}